### ISSUE TITLE
"REQUIRED" is not a member of a group specified for any attribute

### ISSUE THREAD

**Issue by ms-tech-geek** [ibigrock-ashish/bootstrap#3]
Line 47, Column 74: "REQUIRED" is not a member of a group specified for any attribute

    <input type="text" placeholder="Enter Username" name="uname" required>

✉
Error Line 50, Column 76: "REQUIRED" is not a member of a group specified for any attribute

    <input type="password" placeholder="Enter Password" name="psw" required>

**Comment by ibigrock-ashish** [comment]
Done
