### ISSUE TITLE
Only columns (`.col-*-*`) may be children of `.row`s

### ISSUE THREAD

**Issue by ms-tech-geek** [ibigrock-ashish/bootstrap#7]
E013 Line 25, Column 1:Only columns (`.col-*-*`) may be children of `.row`s

E013 Line 62, Column 1:Only columns (`.col-*-*`) may be children of `.row`s

For more details ---->>> https://github.com/twbs/bootlint/wiki/%7Bthis.props.lint.id%7D

**Comment by ibigrock-ashish** [comment]
Done
